apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-app
  labels:
    app: address-app
spec:
  selector:
    matchLabels:
      app: address-app
  replicas: 1
  template:
    metadata:
      labels:
        app: address-app
    spec:
      containers:
      - name: address-app
        image: vinoth157/springbootk8sdemo-addressservice:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8051

---

apiVersion: v1
kind: Service
metadata:
  name: address-app-svc
spec:
  selector:
    app: address-app
  ports:
  - port: 80
    targetPort: 8051