apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  selector:
    matchLabels:
      app: cloud-config
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: vinoth157/springbootk8sdemo-cloudconfig:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8053

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-svc
spec:
  selector:
    app: cloud-config
  ports:
  - port: 80
    targetPort: 8053