apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    name: cloud-gateway
spec:
  selector:
    matchLabels:
      app: cloud-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: vinoth157/springbootk8sdemo-cloudgateway:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8054

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway
  ports:
  - port: 80
    targetPort: 8054
    protocol: TCP