apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-app
spec:
  selector:
    matchLabels:
      app: parent-app
  replicas: 1
  template:
    metadata:
      labels:
        app: parent-app
    spec:
      containers:
      - name: parent-app
        image: vinoth157/springbootk8sdemo-parentservice:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8052

---
apiVersion: v1
kind: Service
metadata:
  name: parent-app-svc
spec:
  selector:
    app: parent-app
  ports:
  - port: 80
    targetPort: 8052